In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"/home/aadarsh/Downloads/global_sales_dataset_234x15.csv")
df

,Order ID,Order Date,Country,Region,Sub-Region,Category,Product Name,Units Sold,Unit Price ($),Discount,Total Sales ($),Sales Channel,Payment Method,Shipping Mode,Order Status
0,ORD-2026-1001,2026-01-01,India,Asia,South Asia,Apparel,Sports Hoodie,22,265.56,0.15,4965.97,Direct Sales,Crypto,Express Courier,Completed
1,ORD-2026-1002,2026-01-02,Germany,Europe,Western Europe,Books & Media,Biography,17,414.07,0.00,7039.19,Wholesale Partner,Credit Card,Express Courier,Completed
2,ORD-2026-1003,2026-01-03,United Arab Emirates,Middle East,GCC,Home & Kitchen,Blender,13,17.31,0.10,202.53,Direct Sales,Crypto,Express Courier,Completed
3,ORD-2026-1004,2026-01-04,Australia,Oceania,Australasia,Home & Kitchen,Air Fryer,1,439.15,0.00,439.15,Direct Sales,PayPal,Standard Shipping,Completed
4,ORD-2026-1005,2026-01-05,France,Europe,Western Europe,Electronics,Wireless Headphones,2,228.48,0.15,388.42,Direct Sales,PayPal,Express Courier,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ORD-2026-1230,2026-09-26,United States,Americas,North America,Apparel,Running Shoes,5,286.77,0.05,1362.16,Online Store,PayPal,Same-Day Delivery,Pending
230,ORD-2026-1231,2026-09-27,United Kingdom,Europe,Western Europe,Apparel,Denim Jacket,4,161.10,0.10,579.96,Retail Mobile App,Credit Card,Economy Freight,Completed
231,ORD-2026-1232,2026-09-28,Canada,Americas,North America,Home & Kitchen,Espresso Machine,24,373.92,0.05,8525.38,Direct Sales,PayPal,Economy Freight,Pending
232,ORD-2026-1233,2026-09-29,France,Europe,Western Europe,Apparel,Cotton T-Shirt,6,172.93,0.15,881.94,Direct Sales,Bank Transfer,Same-Day Delivery,Completed
233,ORD-2026-1234,2026-10-01,South Korea,Asia,East Asia,Electronics,Mechanical Keyboard,2,29.89,0.10,53.80,Wholesale Partner,PayPal,Express Courier,Completed

In [4]:
df[df['Units Sold']<2]

,Order ID,Order Date,Country,Region,Sub-Region,Category,Product Name,Units Sold,Unit Price ($),Discount,Total Sales ($),Sales Channel,Payment Method,Shipping Mode,Order Status
3,ORD-2026-1004,2026-01-04,Australia,Oceania,Australasia,Home & Kitchen,Air Fryer,1,439.15,0.00,439.15,Direct Sales,PayPal,Standard Shipping,Completed
7,ORD-2026-1008,2026-01-09,United Kingdom,Europe,Western Europe,Apparel,Leather Belt,1,327.53,0.10,294.78,Wholesale Partner,Credit Card,Economy Freight,Completed
30,ORD-2026-1031,2026-02-05,South Korea,Asia,East Asia,Books & Media,Sci-Fi Novel,1,53.22,0.05,50.56,Retail Mobile App,Crypto,Economy Freight,Completed
35,ORD-2026-1036,2026-02-11,Singapore,Asia,Southeast Asia,Home & Kitchen,Robot Vacuum,1,278.65,0.00,278.65,Retail Mobile App,PayPal,Standard Shipping,Refunded
47,ORD-2026-1048,2026-02-25,France,Europe,Western Europe,Home & Kitchen,Ergonomic Chair,1,35.92,0.20,28.74,Direct Sales,Credit Card,Standard Shipping,Completed
74,ORD-2026-1075,2026-03-28,Japan,Asia,East Asia,Electronics,Wireless Headphones,1,159.77,0.10,143.79,Wholesale Partner,Crypto,Same-Day Delivery,Pending
125,ORD-2026-1126,2026-05-27,South Korea,Asia,East Asia,Apparel,Denim Jacket,1,177.88,0.05,168.99,Retail Mobile App,PayPal,Same-Day Delivery,Shipped
143,ORD-2026-1144,2026-06-17,France,Europe,Western Europe,Electronics,Smartwatch,1,357.69,0.00,357.69,Retail Mobile App,Credit Card,Standard Shipping,Completed
212,ORD-2026-1213,2026-09-06,India,Asia,South Asia,Fitness & Outdoors,Fitness Tracker,1,445.10,0.00,445.10,Retail Mobile App,PayPal,Same-Day Delivery,Shipped

In [5]:
specific_countries=['France']
df[df['Country'].isin(specific_countries)]

,Order ID,Order Date,Country,Region,Sub-Region,Category,Product Name,Units Sold,Unit Price ($),Discount,Total Sales ($),Sales Channel,Payment Method,Shipping Mode,Order Status
4,ORD-2026-1005,2026-01-05,France,Europe,Western Europe,Electronics,Wireless Headphones,2,228.48,0.15,388.42,Direct Sales,PayPal,Express Courier,Completed
12,ORD-2026-1013,2026-01-15,France,Europe,Western Europe,Home & Kitchen,Espresso Machine,17,436.08,0.00,7413.36,Online Store,Bank Transfer,Standard Shipping,Completed
18,ORD-2026-1019,2026-01-22,France,Europe,Western Europe,Books & Media,Business Strategy,23,348.98,0.00,8026.54,Wholesale Partner,Apple Pay,Same-Day Delivery,Shipped
25,ORD-2026-1026,2026-01-30,France,Europe,Western Europe,Electronics,Mechanical Keyboard,17,212.61,0.15,3072.21,Retail Mobile App,Credit Card,Express Courier,Completed
44,ORD-2026-1045,2026-02-21,France,Europe,Western Europe,Books & Media,Biography,3,179.96,0.10,485.89,Direct Sales,Bank Transfer,Same-Day Delivery,Completed
47,ORD-2026-1048,2026-02-25,France,Europe,Western Europe,Home & Kitchen,Ergonomic Chair,1,35.92,0.20,28.74,Direct Sales,Credit Card,Standard Shipping,Completed
58,ORD-2026-1059,2026-03-09,France,Europe,Western Europe,Books & Media,Sci-Fi Novel,14,270.91,0.00,3792.74,Direct Sales,PayPal,Same-Day Delivery,Pending
89,ORD-2026-1090,2026-04-15,France,Europe,Western Europe,Electronics,Smartwatch,24,229.88,0.00,5517.12,Retail Mobile App,Bank Transfer,Same-Day Delivery,Refunded
91,ORD-2026-1092,2026-04-17,France,Europe,Western Europe,Electronics,Mechanical Keyboard,2,59.77,0.10,107.59,Retail Mobile App,Crypto,Express Courier,Completed
116,ORD-2026-1117,2026-05-16,France,Europe,Western Europe,Fitness & Outdoors,Water Bottle,19,126.37,0.05,2280.98,Wholesale Partner,Apple Pay,Economy Freight,Completed
131,ORD-2026-1132,2026-06-03,France,Europe,Western Europe,Electronics,Wireless Headphones,17,68.42,0.10,1046.83,Online Store,PayPal,Same-Day Delivery,Shipped
140,ORD-2026-1141,2026-06-14,France,Europe,Western Europe,Fitness & Outdoors,Fitness Tracker,16,180.00,0.00,2880.00,Direct Sales,Credit Card,Same-Day Delivery,Completed
143,ORD-2026-1144,2026-06-17,France,Europe,Western Europe,Electronics,Smartwatch,1,357.69,0.00,357.69,Retail Mobile App,Credit Card,Standard Shipping,Completed
157,ORD-2026-1158,2026-07-03,France,Europe,Western Europe,Apparel,Cotton T-Shirt,13,87.00,0.00,1131.00,Direct Sales,PayPal,Same-Day Delivery,Completed
170,ORD-2026-1171,2026-07-19,France,Europe,Western Europe,Fitness & Outdoors,Fitness Tracker,6,95.24,0.05,542.87,Retail Mobile App,Credit Card,Express Courier,Shipped
196,ORD-2026-1197,2026-08-18,France,Europe,Western Europe,Apparel,Leather Belt,15,363.33,0.05,5177.45,Retail Mobile App,Crypto,Economy Freight,Refunded
216,ORD-2026-1217,2026-09-11,France,Europe,Western Europe,Books & Media,Sci-Fi Novel,6,425.82,0.00,2554.92,Retail Mobile App,PayPal,Standard Shipping,Shipped
227,ORD-2026-1228,2026-09-23,France,Europe,Western Europe,Apparel,Sports Hoodie,19,321.22,0.05,5798.02,Retail Mobile App,Crypto,Express Courier,Completed
232,ORD-2026-1233,2026-09-29,France,Europe,Western Europe,Apparel,Cotton T-Shirt,6,172.93,0.15,881.94,Direct Sales,Bank Transfer,Same-Day Delivery,Completed

In [6]:
df

,Order ID,Order Date,Country,Region,Sub-Region,Category,Product Name,Units Sold,Unit Price ($),Discount,Total Sales ($),Sales Channel,Payment Method,Shipping Mode,Order Status
0,ORD-2026-1001,2026-01-01,India,Asia,South Asia,Apparel,Sports Hoodie,22,265.56,0.15,4965.97,Direct Sales,Crypto,Express Courier,Completed
1,ORD-2026-1002,2026-01-02,Germany,Europe,Western Europe,Books & Media,Biography,17,414.07,0.00,7039.19,Wholesale Partner,Credit Card,Express Courier,Completed
2,ORD-2026-1003,2026-01-03,United Arab Emirates,Middle East,GCC,Home & Kitchen,Blender,13,17.31,0.10,202.53,Direct Sales,Crypto,Express Courier,Completed
3,ORD-2026-1004,2026-01-04,Australia,Oceania,Australasia,Home & Kitchen,Air Fryer,1,439.15,0.00,439.15,Direct Sales,PayPal,Standard Shipping,Completed
4,ORD-2026-1005,2026-01-05,France,Europe,Western Europe,Electronics,Wireless Headphones,2,228.48,0.15,388.42,Direct Sales,PayPal,Express Courier,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ORD-2026-1230,2026-09-26,United States,Americas,North America,Apparel,Running Shoes,5,286.77,0.05,1362.16,Online Store,PayPal,Same-Day Delivery,Pending
230,ORD-2026-1231,2026-09-27,United Kingdom,Europe,Western Europe,Apparel,Denim Jacket,4,161.10,0.10,579.96,Retail Mobile App,Credit Card,Economy Freight,Completed
231,ORD-2026-1232,2026-09-28,Canada,Americas,North America,Home & Kitchen,Espresso Machine,24,373.92,0.05,8525.38,Direct Sales,PayPal,Economy Freight,Pending
232,ORD-2026-1233,2026-09-29,France,Europe,Western Europe,Apparel,Cotton T-Shirt,6,172.93,0.15,881.94,Direct Sales,Bank Transfer,Same-Day Delivery,Completed
233,ORD-2026-1234,2026-10-01,South Korea,Asia,East Asia,Electronics,Mechanical Keyboard,2,29.89,0.10,53.80,Wholesale Partner,PayPal,Express Courier,Completed

In [7]:
df2 = df.set_index('Country')
df2

,Order ID,Order Date,Region,Sub-Region,Category,Product Name,Units Sold,Unit Price ($),Discount,Total Sales ($),Sales Channel,Payment Method,Shipping Mode,Order Status
Country,,,,,,,,,,,,,,
India,ORD-2026-1001,2026-01-01,Asia,South Asia,Apparel,Sports Hoodie,22,265.56,0.15,4965.97,Direct Sales,Crypto,Express Courier,Completed
Germany,ORD-2026-1002,2026-01-02,Europe,Western Europe,Books & Media,Biography,17,414.07,0.00,7039.19,Wholesale Partner,Credit Card,Express Courier,Completed
United Arab Emirates,ORD-2026-1003,2026-01-03,Middle East,GCC,Home & Kitchen,Blender,13,17.31,0.10,202.53,Direct Sales,Crypto,Express Courier,Completed
Australia,ORD-2026-1004,2026-01-04,Oceania,Australasia,Home & Kitchen,Air Fryer,1,439.15,0.00,439.15,Direct Sales,PayPal,Standard Shipping,Completed
France,ORD-2026-1005,2026-01-05,Europe,Western Europe,Electronics,Wireless Headphones,2,228.48,0.15,388.42,Direct Sales,PayPal,Express Courier,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United States,ORD-2026-1230,2026-09-26,Americas,North America,Apparel,Running Shoes,5,286.77,0.05,1362.16,Online Store,PayPal,Same-Day Delivery,Pending
United Kingdom,ORD-2026-1231,2026-09-27,Europe,Western Europe,Apparel,Denim Jacket,4,161.10,0.10,579.96,Retail Mobile App,Credit Card,Economy Freight,Completed
Canada,ORD-2026-1232,2026-09-28,Americas,North America,Home & Kitchen,Espresso Machine,24,373.92,0.05,8525.38,Direct Sales,PayPal,Economy Freight,Pending
France,ORD-2026-1233,2026-09-29,Europe,Western Europe,Apparel,Cotton T-Shirt,6,172.93,0.15,881.94,Direct Sales,Bank Transfer,Same-Day Delivery,Completed
South Korea,ORD-2026-1234,2026-10-01,Asia,East Asia,Electronics,Mechanical Keyboard,2,29.89,0.10,53.80,Wholesale Partner,PayPal,Express Courier,Completed

In [8]:
df.set_index(['Country','Region'],inplace=True)

In [10]:

pd.set_option('display.max.rows',234)
df.sort_index()

                                       Order ID  Order Date      Sub-Region  \
Country              Region
Australia            Oceania      ORD-2026-1004  2026-01-04     Australasia
                     Oceania      ORD-2026-1012  2026-01-13     Australasia
                     Oceania      ORD-2026-1015  2026-01-17     Australasia
                     Oceania      ORD-2026-1016  2026-01-18     Australasia
                     Oceania      ORD-2026-1021  2026-01-24     Australasia
                     Oceania      ORD-2026-1066  2026-03-18     Australasia
                     Oceania      ORD-2026-1071  2026-03-24     Australasia
                     Oceania      ORD-2026-1085  2026-04-09     Australasia
                     Oceania      ORD-2026-1089  2026-04-14     Australasia
                     Oceania      ORD-2026-1093  2026-04-18     Australasia
                     Oceania      ORD-2026-1104  2026-05-01     Australasia
                     Oceania      ORD-2026-1107  2026-05-05     Australasia
                     Oceania      ORD-2026-1108  2026-05-06     Australasia
                     Oceania      ORD-2026-1112  2026-05-11     Australasia
                     Oceania      ORD-2026-1125  2026-05-26     Australasia
                     Oceania      ORD-2026-1131  2026-06-02     Australasia
                     Oceania      ORD-2026-1135  2026-06-07     Australasia
                     Oceania      ORD-2026-1194  2026-08-15     Australasia
                     Oceania      ORD-2026-1202  2026-08-24     Australasia
                     Oceania      ORD-2026-1205  2026-08-28     Australasia
                     Oceania      ORD-2026-1219  2026-09-13     Australasia
Brazil               Americas     ORD-2026-1032  2026-02-06   South America
                     Americas     ORD-2026-1043  2026-02-19   South America
                     Americas     ORD-2026-1049  2026-02-26   South America
                     Americas     ORD-2026-1053  2026-03-02   South America
                     Americas     ORD-2026-1057  2026-03-07   South America
                     Americas     ORD-2026-1088  2026-04-12   South America
                     Americas     ORD-2026-1095  2026-04-21   South America
                     Americas     ORD-2026-1099  2026-04-25   South America
                     Americas     ORD-2026-1101  2026-04-28   South America
                     Americas     ORD-2026-1103  2026-04-30   South America
                     Americas     ORD-2026-1121  2026-05-21   South America
                     Americas     ORD-2026-1124  2026-05-25   South America
                     Americas     ORD-2026-1149  2026-06-23   South America
                     Americas     ORD-2026-1170  2026-07-18   South America
                     Americas     ORD-2026-1182  2026-08-01   South America
                     Americas     ORD-2026-1186  2026-08-05   South America
                     Americas     ORD-2026-1188  2026-08-08   South America
                     Americas     ORD-2026-1190  2026-08-10   South America
                     Americas     ORD-2026-1196  2026-08-17   South America
                     Americas     ORD-2026-1206  2026-08-29   South America
Canada               Americas     ORD-2026-1020  2026-01-23   North America
                     Americas     ORD-2026-1024  2026-01-27   North America
                     Americas     ORD-2026-1051  2026-02-28   North America
                     Americas     ORD-2026-1055  2026-03-05   North America
                     Americas     ORD-2026-1060  2026-03-11   North America
                     Americas     ORD-2026-1070  2026-03-22   North America
                     Americas     ORD-2026-1073  2026-03-26   North America
                     Americas     ORD-2026-1079  2026-04-02   North America
                     Americas     ORD-2026-1082  2026-04-05   North America
                     Americas     ORD-2026-1091  2026-04-16   North America
                     Americas     ORD-2026-1127  2026-05-28   North America
                     Americas     ORD-2026-1168  2026-07-15   North America
                     Americas     ORD-2026-1214  2026-09-07   North America
                     Americas     ORD-2026-1223  2026-09-18   North America
                     Americas     ORD-2026-1224  2026-09-19   North America
                     Americas     ORD-2026-1232  2026-09-28   North America
France               Europe       ORD-2026-1005  2026-01-05  Western Europe
                     Europe       ORD-2026-1013  2026-01-15  Western Europe
                     Europe       ORD-2026-1019  2026-01-22  Western Europe
                     Europe       ORD-2026-1026  2026-01-30  Western Europe
                     Europe       ORD-2026-1045  2026-02-21  Western Europe
                     Europe       ORD-2026-1048  2026-02-25  Western Europe
                     Europe       ORD-2026-1059  2026-03-09  Western Europe
                     Europe       ORD-2026-1090  2026-04-15  Western Europe
                     Europe       ORD-2026-1092  2026-04-17  Western Europe
                     Europe       ORD-2026-1117  2026-05-16  Western Europe
                     Europe       ORD-2026-1132  2026-06-03  Western Europe
                     Europe       ORD-2026-1141  2026-06-14  Western Europe
                     Europe       ORD-2026-1144  2026-06-17  Western Europe
                     Europe       ORD-2026-1158  2026-07-03  Western Europe
                     Europe       ORD-2026-1171  2026-07-19  Western Europe
                     Europe       ORD-2026-1197  2026-08-18  Western Europe
                     Europe       ORD-2026-1217  2026-09-11  Western Europe
                     Europe       ORD-2026-1228  2026-09-23  Western Europe
                     Europe       ORD-2026-1233  2026-09-29  Western Europe
Germany              Europe       ORD-2026-1002  2026-01-02  Western Europe
                     Europe       ORD-2026-1014  2026-01-16  Western Europe
                     Europe       ORD-2026-1042  2026-02-18  Western Europe
                     Europe       ORD-2026-1052  2026-03-01  Western Europe
                     Europe       ORD-2026-1061  2026-03-12  Western Europe
                     Europe       ORD-2026-1069  2026-03-21  Western Europe
                     Europe       ORD-2026-1072  2026-03-25  Western Europe
                     Europe       ORD-2026-1077  2026-03-31  Western Europe
                     Europe       ORD-2026-1084  2026-04-08  Western Europe
                     Europe       ORD-2026-1156  2026-07-01  Western Europe
                     Europe       ORD-2026-1157  2026-07-02  Western Europe
                     Europe       ORD-2026-1162  2026-07-08  Western Europe
                     Europe       ORD-2026-1177  2026-07-26  Western Europe
                     Europe       ORD-2026-1189  2026-08-09  Western Europe
                     Europe       ORD-2026-1207  2026-08-30  Western Europe
                     Europe       ORD-2026-1211  2026-09-04  Western Europe
India                Asia         ORD-2026-1001  2026-01-01      South Asia
                     Asia         ORD-2026-1006  2026-01-06      South Asia
                     Asia         ORD-2026-1009  2026-01-10      South Asia
                     Asia         ORD-2026-1041  2026-02-16      South Asia
                     Asia         ORD-2026-1047  2026-02-23      South Asia
                     Asia         ORD-2026-1050  2026-02-27      South Asia
                     Asia         ORD-2026-1064  2026-03-15      South Asia
                     Asia         ORD-2026-1086  2026-04-10      South Asia
                     Asia         ORD-2026-1102  2026-04-29      South Asia
                     Asia         ORD-2026-1119  2026-05-19      South Asia
                     Asia         ORD-2026-1123  2026-05-23      South Asia
                     Asia         ORD-2026-1129  2026-05-30      South Asia
                     Asia         ORD-2026-1130  2026-06-01      South Asia
                     Asia         ORD-2026-1146  2026-06-19      South Asia
                     Asia         ORD-2026-1147  2026-06-21      South Asia
                     Asia         ORD-2026-1154  2026-06-29      South Asia
                     Asia         ORD-2026-1159  2026-07-05      South Asia
                     Asia         ORD-2026-1160  2026-07-06      South Asia
                     Asia         ORD-2026-1163  2026-07-09      South Asia
                     Asia         ORD-2026-1180  2026-07-29      South Asia
                     Asia         ORD-2026-1183  2026-08-02      South Asia
                     Asia         ORD-2026-1192  2026-08-12      South Asia
                     Asia         ORD-2026-1213  2026-09-06      South Asia
                     Asia         ORD-2026-1227  2026-09-22      South Asia
Japan                Asia         ORD-2026-1018  2026-01-20       East Asia
                     Asia         ORD-2026-1023  2026-01-26       East Asia
                     Asia         ORD-2026-1030  2026-02-03       East Asia
                     Asia         ORD-2026-1074  2026-03-27       East Asia
                     Asia         ORD-2026-1075  2026-03-28       East Asia
                     Asia         ORD-2026-1078  2026-04-01       East Asia
                     Asia         ORD-2026-1136  2026-06-08       East Asia
                     Asia         ORD-2026-1166  2026-07-13       East Asia
                     Asia         ORD-2026-1172  2026-07-20       East Asia
                     Asia         ORD-2026-1193  2026-08-13       East Asia
                     Asia         ORD-2026-1204  2026-08-26       East Asia
                     Asia         ORD-2026-1226  2026-09-21       East Asia
Singapore            Asia         ORD-2026-1007  2026-01-08  Southeast Asia
                     Asia         ORD-2026-1029  2026-02-02  Southeast Asia
                     Asia         ORD-2026-1036  2026-02-11  Southeast Asia
                     Asia         ORD-2026-1056  2026-03-06  Southeast Asia
                     Asia         ORD-2026-1058  2026-03-08  Southeast Asia
                     Asia         ORD-2026-1076  2026-03-29  Southeast Asia
                     Asia         ORD-2026-1080  2026-04-03  Southeast Asia
                     Asia         ORD-2026-1083  2026-04-07  Southeast Asia
                     Asia         ORD-2026-1094  2026-04-19  Southeast Asia
                     Asia         ORD-2026-1118  2026-05-18  Southeast Asia
                     Asia         ORD-2026-1120  2026-05-20  Southeast Asia
                     Asia         ORD-2026-1145  2026-06-18  Southeast Asia
                     Asia         ORD-2026-1150  2026-06-24  Southeast Asia
                     Asia         ORD-2026-1151  2026-06-25  Southeast Asia
                     Asia         ORD-2026-1169  2026-07-16  Southeast Asia
                     Asia         ORD-2026-1179  2026-07-28  Southeast Asia
                     Asia         ORD-2026-1200  2026-08-22  Southeast Asia
                     Asia         ORD-2026-1210  2026-09-02  Southeast Asia
South Korea          Asia         ORD-2026-1022  2026-01-25       East Asia
                     Asia         ORD-2026-1025  2026-01-29       East Asia
                     Asia         ORD-2026-1028  2026-02-01       East Asia
                     Asia         ORD-2026-1031  2026-02-05       East Asia
                     Asia         ORD-2026-1037  2026-02-12       East Asia
                     Asia         ORD-2026-1038  2026-02-13       East Asia
                     Asia         ORD-2026-1040  2026-02-15       East Asia
                     Asia         ORD-2026-1054  2026-03-04       East Asia
                     Asia         ORD-2026-1062  2026-03-13       East Asia
                     Asia         ORD-2026-1063  2026-03-14       East Asia
                     Asia         ORD-2026-1065  2026-03-16       East Asia
                     Asia         ORD-2026-1081  2026-04-04       East Asia
                     Asia         ORD-2026-1087  2026-04-11       East Asia
                     Asia         ORD-2026-1096  2026-04-22       East Asia
                     Asia         ORD-2026-1097  2026-04-23       East Asia
                     Asia         ORD-2026-1098  2026-04-24       East Asia
                     Asia         ORD-2026-1106  2026-05-04       East Asia
                     Asia         ORD-2026-1122  2026-05-22       East Asia
                     Asia         ORD-2026-1126  2026-05-27       East Asia
                     Asia         ORD-2026-1134  2026-06-05       East Asia
                     Asia         ORD-2026-1152  2026-06-26       East Asia
                     Asia         ORD-2026-1167  2026-07-14       East Asia
                     Asia         ORD-2026-1173  2026-07-21       East Asia
                     Asia         ORD-2026-1174  2026-07-22       East Asia
                     Asia         ORD-2026-1175  2026-07-23       East Asia
                     Asia         ORD-2026-1176  2026-07-25       East Asia
                     Asia         ORD-2026-1181  2026-07-30       East Asia
                     Asia         ORD-2026-1201  2026-08-23       East Asia
                     Asia         ORD-2026-1212  2026-09-05       East Asia
                     Asia         ORD-2026-1225  2026-09-20       East Asia
                     Asia         ORD-2026-1234  2026-10-01       East Asia
United Arab Emirates Middle East  ORD-2026-1003  2026-01-03             GCC
                     Middle East  ORD-2026-1010  2026-01-11             GCC
                     Middle East  ORD-2026-1011  2026-01-12             GCC
                     Middle East  ORD-2026-1034  2026-02-08             GCC
                     Middle East  ORD-2026-1035  2026-02-09             GCC
                     Middle East  ORD-2026-1109  2026-05-07             GCC
                     Middle East  ORD-2026-1116  2026-05-15             GCC
                     Middle East  ORD-2026-1137  2026-06-09             GCC
                     Middle East  ORD-2026-1148  2026-06-22             GCC
                     Middle East  ORD-2026-1161  2026-07-07             GCC
                     Middle East  ORD-2026-1164  2026-07-10             GCC
                     Middle East  ORD-2026-1178  2026-07-27             GCC
                     Middle East  ORD-2026-1187  2026-08-06             GCC
                     Middle East  ORD-2026-1195  2026-08-16             GCC
                     Middle East  ORD-2026-1203  2026-08-25             GCC
                     Middle East  ORD-2026-1221  2026-09-15             GCC
United Kingdom       Europe       ORD-2026-1008  2026-01-09  Western Europe
                     Europe       ORD-2026-1017  2026-01-19  Western Europe
                     Europe       ORD-2026-1039  2026-02-14  Western Europe
                     Europe       ORD-2026-1044  2026-02-20  Western Europe
                     Europe       ORD-2026-1046  2026-02-22  Western Europe
                     Europe       ORD-2026-1067  2026-03-19  Western Europe
                     Europe       ORD-2026-1110  2026-05-08  Western Europe
                     Europe       ORD-2026-1113  2026-05-12  Western Europe
                     Europe       ORD-2026-1114  2026-05-13  Western Europe
                     Europe       ORD-2026-1133  2026-06-04  Western Europe
                     Europe       ORD-2026-1138  2026-06-10  Western Europe
                     Europe       ORD-2026-1140  2026-06-12  Western Europe
                     Europe       ORD-2026-1142  2026-06-15  Western Europe
                     Europe       ORD-2026-1153  2026-06-28  Western Europe
                     Europe       ORD-2026-1165  2026-07-12  Western Europe
                     Europe       ORD-2026-1191  2026-08-11  Western Europe
                     Europe       ORD-2026-1199  2026-08-20  Western Europe
                     Europe       ORD-2026-1215  2026-09-08  Western Europe
                     Europe       ORD-2026-1231  2026-09-27  Western Europe
United States        Americas     ORD-2026-1027  2026-01-31   North America
                     Americas     ORD-2026-1033  2026-02-07   North America
                     Americas     ORD-2026-1068  2026-03-20   North America
                     Americas     ORD-2026-1100  2026-04-26   North America
                     Americas     ORD-2026-1105  2026-05-02   North America
                     Americas     ORD-2026-1111  2026-05-09   North America
                     Americas     ORD-2026-1115  2026-05-14   North America
                     Americas     ORD-2026-1128  2026-05-29   North America
                     Americas     ORD-2026-1139  2026-06-11   North America
                     Americas     ORD-2026-1143  2026-06-16   North America
                     Americas     ORD-2026-1155  2026-06-30   North America
                     Americas     ORD-2026-1184  2026-08-03   North America
                     Americas     ORD-2026-1185  2026-08-04   North America
                     Americas     ORD-2026-1198  2026-08-19   North America
                     Americas     ORD-2026-1208  2026-08-31   North America
                     Americas     ORD-2026-1209  2026-09-01   North America
                     Americas     ORD-2026-1216  2026-09-09   North America
                     Americas     ORD-2026-1218  2026-09-12   North America
                     Americas     ORD-2026-1220  2026-09-14   North America
                     Americas     ORD-2026-1222  2026-09-16   North America
                     Americas     ORD-2026-1229  2026-09-25   North America
                     Americas     ORD-2026-1230  2026-09-26   North America

                                            Category  \
Country              Region
Australia            Oceania          Home & Kitchen
                     Oceania           Books & Media
                     Oceania          Home & Kitchen
                     Oceania           Books & Media
                     Oceania                 Apparel
                     Oceania                 Apparel
                     Oceania             Electronics
                     Oceania          Home & Kitchen
                     Oceania      Fitness & Outdoors
                     Oceania      Fitness & Outdoors
                     Oceania      Fitness & Outdoors
                     Oceania             Electronics
                     Oceania      Fitness & Outdoors
                     Oceania          Home & Kitchen
                     Oceania                 Apparel
                     Oceania             Electronics
                     Oceania      Fitness & Outdoors
                     Oceania                 Apparel
                     Oceania      Fitness & Outdoors
                     Oceania          Home & Kitchen
                     Oceania                 Apparel
Brazil               Americas            Electronics
                     Americas                Apparel
                     Americas            Electronics
                     Americas         Home & Kitchen
                     Americas         Home & Kitchen
                     Americas                Apparel
                     Americas     Fitness & Outdoors
                     Americas            Electronics
                     Americas          Books & Media
                     Americas     Fitness & Outdoors
                     Americas            Electronics
                     Americas         Home & Kitchen
                     Americas          Books & Media
                     Americas          Books & Media
                     Americas            Electronics
                     Americas                Apparel
                     Americas                Apparel

In [13]:
df.loc['Australia','Oceania']

/tmp/ipykernel_13263/243407758.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.loc['Australia','Oceania']

                        Order ID  Order Date   Sub-Region            Category  \
Country   Region
Australia Oceania  ORD-2026-1004  2026-01-04  Australasia      Home & Kitchen
          Oceania  ORD-2026-1012  2026-01-13  Australasia       Books & Media
          Oceania  ORD-2026-1015  2026-01-17  Australasia      Home & Kitchen
          Oceania  ORD-2026-1016  2026-01-18  Australasia       Books & Media
          Oceania  ORD-2026-1021  2026-01-24  Australasia             Apparel
          Oceania  ORD-2026-1066  2026-03-18  Australasia             Apparel
          Oceania  ORD-2026-1071  2026-03-24  Australasia         Electronics
          Oceania  ORD-2026-1085  2026-04-09  Australasia      Home & Kitchen
          Oceania  ORD-2026-1089  2026-04-14  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1093  2026-04-18  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1104  2026-05-01  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1107  2026-05-05  Australasia         Electronics
          Oceania  ORD-2026-1108  2026-05-06  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1112  2026-05-11  Australasia      Home & Kitchen
          Oceania  ORD-2026-1125  2026-05-26  Australasia             Apparel
          Oceania  ORD-2026-1131  2026-06-02  Australasia         Electronics
          Oceania  ORD-2026-1135  2026-06-07  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1194  2026-08-15  Australasia             Apparel
          Oceania  ORD-2026-1202  2026-08-24  Australasia  Fitness & Outdoors
          Oceania  ORD-2026-1205  2026-08-28  Australasia      Home & Kitchen
          Oceania  ORD-2026-1219  2026-09-13  Australasia             Apparel

                          Product Name  Units Sold  Unit Price ($)  Discount  \
Country   Region
Australia Oceania            Air Fryer           1          439.15      0.00
          Oceania    Business Strategy           6          104.21      0.05
          Oceania         Robot Vacuum           5          101.79      0.05
          Oceania         Sci-Fi Novel           6          335.27      0.10
          Oceania        Running Shoes          21          235.16      0.05
          Oceania         Leather Belt           6          205.85      0.15
          Oceania  Wireless Headphones          19           43.98      0.05
          Oceania              Blender          24          322.54      0.15
          Oceania         Camping Tent          20          325.62      0.05
          Oceania         Camping Tent           6          248.37      0.10
          Oceania         Dumbbell Set          23          261.00      0.05
          Oceania  Mechanical Keyboard          22          374.66      0.05
          Oceania         Camping Tent          16          432.20      0.00
          Oceania            Air Fryer           4          140.25      0.00
          Oceania         Denim Jacket           6          350.49      0.05
          Oceania  Mechanical Keyboard           2          411.15      0.10
          Oceania             Yoga Mat           9           96.05      0.15
          Oceania        Sports Hoodie          15          133.45      0.05
          Oceania         Water Bottle          19          255.00      0.10
          Oceania     Espresso Machine           5          234.90      0.15
          Oceania         Denim Jacket          23          191.78      0.10

                   Total Sales ($)      Sales Channel Payment Method  \
Country   Region
Australia Oceania           439.15       Direct Sales         PayPal
          Oceania           594.00  Wholesale Partner  Bank Transfer
          Oceania           483.50       Online Store    Credit Card
          Oceania          1810.46  Retail Mobile App      Apple Pay
          Oceania          4691.44       Direct Sales         PayPal
          Oceania          1049.83  Retail Mobile App      Apple Pay
          Oceania           793.84  Retail Mobile App  Bank Transfer
          Oceania          6579.82       Direct Sales  Bank Transfer
          Oceania          6186.78       Direct Sales  Bank Transfer
          Oceania          1341.20  Retail Mobile App    Credit Card
          Oceania          5702.85       Online Store      Apple Pay
          Oceania          7830.39  Wholesale Partner    Credit Card
          Oceania          6915.20  Wholesale Partner  Bank Transfer
          Oceania           561.00  Wholesale Partner         Crypto
          Oceania          1997.79  Retail Mobile App         Crypto
          Oceania           740.07  Wholesale Partner      Apple Pay
          Oceania           734.78  Wholesale Partner         Crypto
          Oceania          1901.66  Wholesale Partner         Crypto
          Oceania          4360.50       Direct Sales    Credit Card
          Oceania           998.32       Direct Sales         PayPal
          Oceania          3969.85       Direct Sales      Apple Pay

                       Shipping Mode Order Status
Country   Region
Australia Oceania  Standard Shipping    Completed
          Oceania    Economy Freight    Completed
          Oceania    Economy Freight    Completed
          Oceania  Standard Shipping     Refunded
          Oceania    Express Courier     Refunded
          Oceania    Express Courier      Shipped
          Oceania  Standard Shipping    Completed
          Oceania  Same-Day Delivery    Completed
          Oceania  Same-Day Delivery    Completed
          Oceania    Express Courier      Shipped
          Oceania    Express Courier      Pending
          Oceania  Standard Shipping     Refunded
          Oceania    Express Courier     Refunded
          Oceania    Express Courier      Shipped
          Oceania    Economy Freight    Completed
          Oceania  Same-Day Delivery    Completed
          Oceania  Standard Shipping      Shipped
          Oceania  Same-Day Delivery    Completed
          Oceania  Same-Day Delivery    Completed
          Oceania    Express Courier      Shipped
          Oceania    Express Courier      Shipped